# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                
language: python    

# Versão que a aplicação suporta.                                                                                                                 
python:     
  - "3.7.9"     

#Build Environments
os: linux
dist: xenial

# Instalação de Módulos que são necessários para a Aplicação.                                                                                     
install:     
  - pip install flask


# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                     
script:     
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  - provider: heroku
    strategy: api 
    api_key: $HEROKU_API_KEY
    edge: true 
    app: devopslab-salomao                                                                                                                      
    on: 
      branch: main
  - provider: gae
    keyfile: ../devopslab-salomao-bd72a5139035.json
    project: devopslab-salomao
    on:
      branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_2dde5485a8f1_key -iv $encrypted_2dde5485a8f1_iv
  -in devopslab-salomao-bd72a5139035.json.enc -out ../devopslab-salomao-bd72a5139035.json
  -d