# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                
language: python    

# Versão que a aplicação suporta.                                                                                                                 
python:     
  - "3.7.9"     

#Build Environments
os: linux
dist: xenial

# Instalação de Módulos que são necessários para a Aplicação.                                                                                     
install:     
  - pip install flask


# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                     
script:     
  - python -m unittest -v test

# Definir o Deploy no Heroku
deploy:
  - provider: heroku
    strategy: api 
    api_key: $HEROKU_API_KEY
    edge: true 
    app: devopslab-salomao                                                                                                                      
    on: 
      branch: main
  - provider: gae
    keyfile: ../lab-devops-cloud-322914-6897f2349e8f.json
    project: lab-devops-cloud-322914
    on:
      branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_67504dfe6695_key -iv $encrypted_67504dfe6695_iv
  -in lab-devops-cloud-322914-6897f2349e8f.json.enc -out ../lab-devops-cloud-322914-6897f2349e8f.json
  -d